### PR TITLE
#234 handle comma separated hostnames in known_hosts

### LINKED ISSUE #234: known_hosts not read properly for setting server_host_key
Problem:
Given `known_hosts` with `server,127.0.0.1  ecdsa-sha2-nistp256 ...` and on the client side, we are connecting using the hostname `server`.
groovy-ssh cannot find an entry for `server`, as the entry in the hostname is treated as `server,127.0.0.1` instead of two different ones.
The `server_host_key` property is not set for Jsch, which may cause unexpected authentication errors.

Possible Fix:
Change [HostKeyRepository.compare(HostKey, host, port)](https://github.com/int128/groovy-ssh/blob/986e7a630dcc5a853df040f11878a5faf2dfdaec/core/src/main/groovy/org/hidetake/groovy/ssh/connection/HostKeyRepository.groovy#L58) to consider multiple hosts in given `HostKey` as well. 
unfortunately `Jsch`'s `HostKey.isMatched(host)` method is package private and i'm not sure if it is worth to call it using reflection or something similar.

### PR DESCRIPTION
**Pull request by AarjavP**
fixes #234 and should not break anything, based on my understanding of [known_hosts fomat](http://man.openbsd.org/sshd.8#SSH_KNOWN_HOSTS_FILE_FORMAT)

I have added a couple of unit tests for hashed keys as well, but I am not sure about their accuracy.

As I was doing this, I also noticed that in the hashing algo might change based on `jsch.getConfig('hmac-sha1')`, is this something that should be handled on the groovy side as well?

### CODE REVIEW

**Comment by AarjavP** [comment]
@int128 Anything I can do to speed this up? Are you waiting on #236 to be fixed first?

**Comment by int128** [comment]
Thank you for the contribution and sorry for the late reply.
I will rebase your commit and merge it later.

**Comment by AarjavP** [comment]
whoops, I clicked on update branch on github website thinking it may give option to rebase but it just did the merge on it its own. Wanted to see if the build / tests pass.

**Comment by int128** [comment]
Merged.

**Pull request closed without merging**
