### PR TITLE
Close gateway session

### PR DESCRIPTION
**Pull request by timend**
This fixes the issue https://github.com/int128/groovy-ssh/issues/71.

### CODE REVIEW

**Comment by timend** [comment]
I'll investigate the test failure. The new assertion passes successfully and stable on my Windows 8 machine.

What never worked was this assertion:
```targetServer.activeSessions.size() == 0```

Probably a timing issue between client and server side.

**Comment by int128** [comment]
Yes, it may be a timing issue. It passes on my Mac but not on Circle CI Linux.

**Comment by int128** [comment]
Great! Server integration tests passed. I will cherry pick your commit.

**Comment by timend** [comment]
I've improved upon the timing a little with Spock's PollingConditions.

**Comment by int128** [comment]
Cool. Now Gradle SSH Plugin and Groovy SSH 2.4.3 has been released. Thank you for the contribution.

**Pull request closed without merging**
