### PR TITLE
fix: use `archiveClassifier` instead of `classifier` for cli shadowJa…

### PR DESCRIPTION
**Pull request by chenrui333**
This adds the feature | fixes the bug #350 
followup #351 

relates to https://github.com/Homebrew/homebrew-core/pull/165283

cc @elijahfhopp

### CODE REVIEW

**Comment by chenrui333** [comment]
I see, going to bump the wrapper as well.

**Comment by chenrui333** [comment]
cc @int128 good to be merged, thanks!

**Review by int128 — APPROVED** [review]
Thanks!

**Comment by chenrui333** [comment]
hi folks, any chance to cut a new release? Thanks!

**Pull request merged**
